server:
  port: 8084

spring:
  application:
    name: contactManager

# Configuration  PostgreSQL
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:contactManager}?useSSL=false
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:nabil}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: postgres
# Configuration Hibernate
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update
                #create-drop
    show-sql: true
    database: postgresql

myapp:
  constant:
    SECRET_KEY: "qwertyuiopasdfghjklzxcvbnm123456"




